LICENSE
`LICENSE` file is missing in this project, `libplanet-explorer-frontend`.
so I suggest to apply `MIT` license.
=> Missing license file

src/api.graphql, src/schema.graphql
This follows the changes made by <https://github.com/planetarium/libplanet-explorer/pull/39>.
=> Update GraphQL schema

src/components/Layout.tsx
Addresses the first feature of the issue #5.
=> Navigate to block page by its hash

src/pages/block.tsx
Close https://github.com/planetarium/libplanet-explorer-frontend/issues/1
=> Block previous hash and difficulty

src/api.graphql, src/pages/block.tsx
This fixes #3.
p.s. Please check my code syntax(especially indent) is okay.
=> Add transaction list to block page

.editorconfig, src/pages/index.tsx
=> Recent blocks summary

src/misc/useQueryString.ts
Resolves https://github.com/planetarium/libplanet-explorer-frontend/issues/14
=> Fix rendering issue

package-lock.json, src/api.graphql, src/pages/block.tsx, src/pages/transaction.tsx, src/schema.graphql
NOTE: planetarium/libplanet-explorer#52 should be merged before this PR.
Added transaction detail page. (fixes #10)
=> Add transaction page

package-lock.json, src/api.graphql, src/pages/index.tsx, src/schema.graphql
Close #28 
- Make an option to list only blocks having any tx. See above screenshot.
- Re-formatting the code.
- Clarify interval & difficulty message
**note:** It has to be merged after the bug on PR (https://github.com/planetarium/libplanet-explorer/pull/53/files) is fixed.
=> Make an option to list only blocks having any tx

.dockerignore, Dockerfile, docker-compose.yml
Multi stage docker build reduced the image size from 1.1GB to just 25MB.
We can run docker-compose up to run the application
Signed-off-by: kmjayadeep@gmail.com <kmjayadeep@gmail.com>
=> added multi stage docker build, added docker compose

src/api.graphql, src/pages/index.tsx
=> Add miner column

src/pages/block.tsx
=> Add transactions count next to the label

src/pages/index.tsx
=> Add difficulty in index page

src/api.graphql, src/pages/transaction.tsx
=> Add actions in transaction page.

src/pages/block.tsx
=> Show transactions in table at block page

src/pages/block.tsx
=> Added navigation to previous hash

src/api.graphql, src/pages/block.tsx, src/pages/index.tsx, src/pages/transaction.tsx, src/schema.graphql
Works with https://github.com/planetarium/libplanet-explorer/pull/78
Added `transactions` query which is not yet used.
=> Refactoring query

DEPLOYMENTS.tsv
=> Add 9c testnet for multi-miner to DEPLOYMENTS.tsv

src/components/Layout.tsx, src/pages/block.tsx, src/pages/transaction.tsx
This PR aids some links that hadn't matched path properly.
=> Fix broken links

DEPLOYMENTS.tsv
This PR updates 9c-alpha's backend endpoint as the production cluster.
=> Apply 9c-alpha(production) endpoint

src/index.css, src/pages/index.tsx
This patch redesign key numbers view.
=> Add key numbers panel design

src/api.graphql
fix https://github.com/planetarium/libplanet-explorer-frontend/issues/60
=> Make the latest transaction first in the account page

src/pages/index.tsx
=> Add shimmer

src/pages/account.tsx
=> Fix a bug that tx list hadn't displayed all txs in account page

src/components/Timestamp.tsx, src/pages/account.tsx, src/pages/block.tsx, src/pages/index.tsx, src/pages/transaction.tsx
=> Show timestamps in local time zone

DEPLOYMENTS.tsv
=> Update graphql endpoint on 9c-alpha network

gatsby-node.js
This patch collects subpage files automatically by `fs.readdir`.
=> Read subpages by fs.readdir

src/api.graphql, src/schema.graphql
Additionally, this patch updates `DEPLOYMENTS.tsv`.
=> Refactor transaction query

src/subpages/list.tsx
This PR adds comma to every three digits.
=> Add a thousands separator to block index and difficulty

src/subpages/list.tsx
=> Add a link from the miner column to account page

src/api.graphql, src/components/BlockList.tsx, src/components/Layout.tsx, src/components/List.tsx, src/components/OffsetSwitch.tsx, src/misc/columns.tsx, src/misc/graphQLEndPoint.ts, src/misc/useOffset.ts, src/pages/index.tsx, src/schema.graphql, src/subpages/account.tsx, src/subpages/list.tsx
=> Add Mined Block list in account page

src/misc/columns.tsx
continue from #100
| Before | After |
| :-: | :-: |
| <img width="185" alt="Screen Shot 2020-08-18 at 4 57 41 PM" src="https://user-images.githubusercontent.com/5278201/90486501-0126d700-e174-11ea-82d8-470cae1d6b05.png"> | <img width="219" alt="Screen Shot 2020-08-18 at 4 21 35 PM" src="https://user-images.githubusercontent.com/5278201/90486513-06842180-e174-11ea-950b-9e6dac1c6bb7.png"> |
=> Increase the width of the index column

.eslintrc.js
There are no specified rules for React.
| Before | After |
| :-: | :-: |
| <img width="385" alt="Screen Shot 2020-08-19 at 1 11 47 PM" src="https://user-images.githubusercontent.com/5278201/90591612-8961b680-e21e-11ea-8e16-edbedada5da8.png"> | <img width="385" alt="Screen Shot 2020-08-19 at 1 18 18 PM" src="https://user-images.githubusercontent.com/5278201/90591622-8cf53d80-e21e-11ea-9e42-21484bf9dc3b.png"> |
| eslint(@typescript-eslint/no-unused-vars) | |
=> Use eslint-plugin-react preset

src/api.graphql, src/components/List.tsx, src/components/OffsetSwitch.tsx, src/misc/columns.tsx, src/misc/useOffset.ts, src/subpages/account.tsx, src/subpages/list.tsx
=> Add offset control for Transaction List

src/subpages/account.tsx
=> Show colon in title if there is have items

src/subpages/list.tsx
=> Restore auto-update (by polling) on the block list

src/index.css
| Before |
| :--: |
| <img width="1210" alt="Screen Shot 2020-09-25 at 6 04 22 PM" src="https://user-images.githubusercontent.com/5278201/94248807-f2dd8f00-ff59-11ea-8572-34a55ddaff1f.png">
| **After** |
| <img width="1103" alt="Screen Shot 2020-09-25 at 6 05 12 PM" src="https://user-images.githubusercontent.com/5278201/94248841-fffa7e00-ff59-11ea-928c-c9616dca6e05.png"> |
=> Add line break for signature

package-lock.json, package.json, src/api.graphql, src/schema.graphql, src/subpages/account.tsx, src/subpages/transaction.tsx
It resolves break changes in https://github.com/planetarium/libplanet-explorer/pull/131
=> feat: apply action type restruction

.github/auto_assign.yml
=> Remove me from auto assign reviewers

codegen.yml, src/api.graphql, src/schema.graphql, src/subpages/block.tsx
=> feat: add total difficulty field

DEPLOYMENTS.tsv
=> chore: remote useless endpoint and add community mining

src/api.graphql, src/subpages/account.tsx
Resolves #61.
Missing Nonces, which cannot be present unless there is a libplanet bug, has been removed, and the query has been updated accordingly to display correct involved txs and signed txs.
=> Fix account transaction list

src/components/List.tsx, src/misc/columns.tsx, src/subpages/account.tsx, src/subpages/block.tsx, src/subpages/list.tsx
Partially addresses #99.
Because there was not enough space to display blocks and txs side-to-side, I made them into a pivoted display.
=> Transaction list in main page

DEPLOYMENTS.tsv
Adding `9c-mobile` network to `explorer.libplanet.io`.
=> add 9c-mobile

DEPLOYMENTS.tsv
=> fix spacing

lib/listColumns.tsx, pages/[endpoint].tsx, pages/[endpoint]/block.tsx, src/api.graphql, src/schema.graphql
This PR adjusts GraphQL schema and layout to prepare PBFT. (it is still compatible with PoW networks such as Nine Chronicles mainnet).
=> Prepare PBFT

lib/listColumns.tsx, package.json, pages/[endpoint].tsx, yarn.lock
=> feat: mapping with proposer address to name

README.md, pages/[endpoint].tsx, pages/[endpoint]/account.tsx, src/api.graphql
Resolves #195. Added staged tx view on the main list page and account page and consolidated tables on the account page in a `Pivot` component.
=> Polish UI and add staged tx view

README.md, pages/[endpoint].tsx, pages/[endpoint]/account.tsx, src/api.graphql
Contents equal to #196. For testing preview deployments.
=> Preview deployment test for #196

DEPLOYMENTS.tsv
=> Update DEPLOYMENTS.tsv for internal-mead

DEPLOYMENTS.tsv
=> Leave 9c-internal

DEPLOYMENTS.tsv
=> Add mainnet idun endpoint

DEPLOYMENTS.tsv
=> add 9c-dev-v2 endpoint

DEPLOYMENTS.tsv
=> fix format
