package.json
It resolves #26. 
Before this, there was errors when we run `npm run dev:prettier` in windows environment.
To run the command, we should use double quotations (`"`), not single quotation (`'`).
=> Make available in windows

src/api.graphql, src/pages/index.tsx
close https://github.com/planetarium/libplanet-explorer-frontend/issues/22
=> Tx # in block list

README.md
=> Fix GitHub Action badge and link

src/pages/index.tsx
This resolves #30.
The column, `Time Taken`, will display each block's interval like below..
Also I made frontend calculate the time taken in frontend, but it won't be correct when `excludeEmptyTx` is true.
So IMO it should be calculated in [planetarium/libplanet-explorer].
PS. I opened the issue about that, planetarium/libplanet-explorer#66
[planetarium/libplanet-explorer]: https://github.com/planetarium/libplanet-explorer
=> Add time taken column

DEPLOYMENTS.tsv, src/pages/index.tsx
Implements #37 
According to comments in issue and on discord, list will be refreshed if there are new items in it (new blocks added) or blocks with the same index have different hash (chain was swapped) - thus telling React to rerender the list.
=> Auto refresh page

src/pages/account.tsx
There was a bug `AccountPage` shows transactions except the last, not all transactions.
I fixed it. And I also made `AccountPage` show missing nonces of the signed transactions.
=> Make account page show all txs and missing nonces

DEPLOYMENTS.tsv
It's also a workaround for the bug #66.
=> Clean up obsolete endpoints and change the default endpoint

build.sh
The current GitHub page setting expects `_site` is a base directory.
This patch renames Gatsby's default output directory(`public`) to `_site`.
=> Fix output directory issue

gatsby-node.js
This fixes the routing issue for generated paths by `gatsby-node.js`.
=> Add isPermanent to generated paths

DEPLOYMENTS.tsv
I'm sorry but there was issue that there was *space*, not *tab* in *DEPLOYMENTS.tsv*.
So, in this pull request, I fixed it and removed disabled deployment (i.e., ground-zero).
=> Fix space-tab issue in DEPLOYMENTS.tsv

src/components/Timestamp.tsx
Reference issue: #92
`dateStyle` and `timeStyle` options not yet implemented in some browsers.
I replace this options to output same result. (tested in chrome console):
=> Replace Intl format options for Browser compatibility

src/subpages/transaction.tsx
Used `JSON.stringfy` [`space` argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_space_argument) and `<pre />` tag.
| Before | After |
| :-: | :-: |
| <img width="386" alt="Screen Shot 2020-08-04 at 5 21 50 PM" src="https://user-images.githubusercontent.com/5278201/89271111-3bbe4900-d677-11ea-8ba2-834ad9ffe1ee.png">| <img width="526" alt="Screen Shot 2020-08-04 at 5 21 32 PM" src="https://user-images.githubusercontent.com/5278201/89271135-424cc080-d677-11ea-9a1e-305f387ec402.png"> |
[`tx?e09bc5a3f5bc0bf5eec31ed0598fb4158cbdb6967a734fa4f6bdc78a9d346d91`](https://explorer.libplanet.io/9c-beta/transaction/?e09bc5a3f5bc0bf5eec31ed0598fb4158cbdb6967a734fa4f6bdc78a9d346d91)
=> Show action values with indent in transaction page

gatsby-node.js
This fixes an issue where path routing was not working properly when accessing a subpage directly.
For example, you can't access the transaction and account pages from the page below:
http://explorer.libplanet.io/9c-beta/block?c98d5d3ad38cd78dadfd6af5a73c6a9bd82654b241687c473f8f691143000000
=> Fix subpage routing

.github/auto_assign.yml
> [code review assignment for your team - GitHub Docs](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team#configuring-code-review-assignment)
Upper feature is not woking in our repository. so I add config for [auto-assign](https://github.com/kentaro-m/auto-assign) github bot.
=> Set auto assign by github bot

.github/auto_assign.yml
It must be explicitly written as 0 so that all reviewers is specified.
(Example: https://github.com/planetarium/auto-assign-test#2)
Reference: https://github.com/kentaro-m/auto-assign#single-reviewers-list
=> Add number of reviewers

src/index.css
I added monospace font-style to link in Account Details page and codes in Transaction Details page.
close #115
=> Display hex values with monospace font

src/api.graphql, src/schema.graphql, src/subpages/transaction.tsx
It provides the view for the `blockRef` field of the `Transaction` type.
If the transaction had contained in many blocks, then it will show all the blocks.
But sadly, planetarium/libplanet-explorer has many issues and the explorer in 9c-main doesn't work well for the `blockRef` field. This pull request should be merged after the issues fixed.
PS. The below screenshot has taken in my local environment.
=> feat(tx-page): provide block reference field

src/subpages/transaction.tsx
The new view for actions' plain view was introduced at #124. But it doesn't handle all types of `BencodexValue` successfully and fully. This pull request fixes it and applies lint not applied in #124. I found a solution from planetarium/bencodex-viewer codes so I thanks to @dahlia. 🙇 It will be cooler if it uses planetarium/bencodex-viewer as a React component.
=> fix(tx-page): handle 'bigint'-typed bencodex value

src/misc/columns.tsx, src/subpages/account.tsx, src/subpages/list.tsx
The miner links on both the Main page and the Account page used the same "mineColumns" prop and this caused the miner link in the account page to go to '.../account/account/...' which does not exist.
There might be a more efficient way to do this but I created a separate prop for the accounts page and now the relative path will correctly navigate. Let me know if there are other ways to make this fix more efficient!
=> update correct paths on account page

src/subpages/account.tsx
this PR temporarily modifies the query that originally requested all transactions to the most recent 101 transactions. If either "signed transactions", "involved transactions" or "missing nonces" are greater than 100, the count will render "100+".
**Note)** I found that the "desc" option in these queries almost doubles the response time so it might be a good place to look into for further optimization.
**Before:**
**After:**
=> modify transactions count query

README.md
As GitHub Actions is not used for deployment, the build status badge is no more needed either.
=> Remove GitHub Actions build status badge

DEPLOYMENTS.tsv
I'm adding a testing url for 9c-main to understand why the GraphQL upgrade version(https://github.com/planetarium/NineChronicles.Headless/tree/v100097-gql) of the headless won't load on the explorer as below.
It's not an API type error because it works fine on the `https://d131807iozwu1d.cloudfront.net/ui/playground` endpoint and the console says that the error is from cloudfront. I've tried to reproduce the error on my local PC but it works fine, which is why I'm pretty sure it's a cloudfront-related issue. So I'm trying to bypass it by adding the load balancer url directly to further investigate the issue.
=> add test url

DEPLOYMENTS.tsv
Removing the unnecessary `/` path at the end of the GraphQL endpoints because this seems to be the problem preventing the upgraded GQL headless data from being rendered on the frontend.
Error
Fix
=> remove unnecessary url path

src/misc/useOffset.ts
This PR fixes the `{offset: "50", limit: 50, excludeEmptyTxs: false}` variable to `{offset: 50, limit: 50, excludeEmptyTxs: false}`.
This previously worked in the earlier GQL version but type enforcement became stricter in the new GQL so it returns an error.
Error example:
=> fix offset data type

DEPLOYMENTS.tsv
This pull request removes *9c-content-rating*, not working, and adds a new endpoint for temporary bridge auditing.
- @tkiapril: Maybe this repository's current maintainer.
- @longfin: Related to the audit.
=> Add 9c-bridge-audit to `DEPLOYMENT.tsv`
